Sprint 4
ofstudio/go-shortener pull request #22
Opened 2022-07-19 20:21 UTC by ofstudio

# Code increment 14

2022-07-20 11:31 UTC, Bazys requested changes
предлагаю избавиться от паники во вспомогательных функциях!
а так, очень шикарный код, хорошо проработан патерн fanIn-fanOut и написаны серьезные тесты. Не забывай поддерживать уровень покрытия тестами на высоком значении. Если ты продолжишь обучение, то на второй половине курса, нет внешних автотестов.

2022-07-20 11:31 UTC, Bazys commented on internal/app/config/compose.go
> +func MustCompose(funcs ...CfgFunc) *Config {
предлагаю все таки придеживаться стиля "don`t panic" и не завершать приложение из этой точки.
По хорошему должен быть просто один конструктор с functional options который  может вернуть ошибку.

2022-07-20 11:31 UTC, Bazys commented on internal/app/config/helpers.go
> +func mustParseRequestURI(rawURL string) url.URL {
а почему бы их не сделать приватными функциями структуры Config ?
и опять паника?
предлагаю придерживаться стиля, что панику можно вызвать только из main либо в крайнем случае из главной функции, которая вызывается из майн.

2022-07-20 11:31 UTC, Bazys commented on internal/app/services/fan-out.go
> +var batchWorkerCount = runtime.NumCPU()
чисто для информации.
в кубере ты получишь общее доступное количество ядер у железа. 
И если на ноду при этом выделят только одно ядро, то можно получить эффект гонки между горутинами и получится только хуже.
для таких случаев есть целая библиотека - https://github.com/uber-go/automaxprocs

2022-07-20 19:45 UTC, ofstudio commented on internal/app/services/fan-out.go
> +var batchWorkerCount = runtime.NumCPU()
Спасибо, поизучал немного: это очень интересно.
Добавил примечание. Значение заменил на константу.

2022-07-20 19:47 UTC, ofstudio commented on internal/app/config/helpers.go
> +func mustParseRequestURI(rawURL string) url.URL {
Внес функции-валидаторы в приватные методы структуры Config.

`randSecret` и `urlParseFunc` оставил отдельностоящими функциями, тк у них вспомогательная роль и объекту `Config` они не специфичны

2022-07-22 12:01 UTC, Bazys approved these changes

2022-07-22 13:01 UTC, merged